export type ColumnDef = { key: string; label: string };

export type ItemMockData = {
  summaryColumns: ColumnDef[];
  summaryData: Record<string, string>[];
  detailsColumns: ColumnDef[];
  detailsData: Record<string, string>[];
};

export const ITEM_MOCK_DATA: Record<string, ItemMockData> = {
  holiday: {
    summaryColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'HolidayCode', label: 'Holiday Code' },
      { key: 'HolidayName', label: 'Holiday Name' },
      { key: 'HolidayAmount', label: 'Holiday Amount' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    summaryData: [
      { id: 's1', state: 'confirmed', RecordID: '1001',
        EmployeeCode: 'E001',
        EmployeeName: 'Li Si',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        HolidayCode: 'H01',
        HolidayName: 'Labor Day',
        HolidayAmount: '1.00',
        AllowanceCode: 'A-OT',
        AllowanceName: 'Holiday OT',
      },
      { id: 's2', state: 'confirmed', RecordID: '1002',
        EmployeeCode: 'E002',
        EmployeeName: 'Wang Wu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        HolidayCode: 'H02',
        HolidayName: 'National Day',
        HolidayAmount: '2.00',
        AllowanceCode: 'A-OT',
        AllowanceName: 'Holiday OT',
      },
    ],
    detailsColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'HolidayCode', label: 'Holiday Code' },
      { key: 'HolidayName', label: 'Holiday Name' },
      { key: 'HolidayDate', label: 'Holiday Date' },
      { key: 'HolidayAmount', label: 'Holiday Amount' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    detailsData: [
      {
        id: 'h1',
        state: 'confirmed',
        RecordID: '2001',
        EmployeeCode: 'E001',
        EmployeeName: 'Li Si',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        HolidayCode: 'H01',
        HolidayName: 'Labor Day',
        HolidayDate: '2026-05-01',
        HolidayAmount: '1.00',
        AllowanceCode: 'A-OT',
        AllowanceName: 'Holiday OT',
        issue: 'Clock-in on statutory holiday',
        severity: 'High',
      },
      {
        id: 'h2',
        state: 'confirmed',
        RecordID: '2002',
        EmployeeCode: 'E002',
        EmployeeName: 'Wang Wu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        HolidayCode: 'H02',
        HolidayName: 'National Day',
        HolidayDate: '2026-10-01',
        HolidayAmount: '1.00',
        AllowanceCode: 'A-OT',
        AllowanceName: 'Holiday OT',
        issue: 'Clock-in on statutory holiday',
        severity: 'High',
      },
      {
        id: 'h3',
        state: 'confirmed',
        RecordID: '2003',
        EmployeeCode: 'E002',
        EmployeeName: 'Wang Wu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        HolidayCode: 'H02',
        HolidayName: 'National Day',
        HolidayDate: '2026-10-02',
        HolidayAmount: '1.00',
        AllowanceCode: 'A-OT',
        AllowanceName: 'Holiday OT',
        issue: 'Clock-in on statutory holiday',
        severity: 'High',
      },
    ]
  },
  attendance: {
    summaryColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
      { key: 'ClockDate', label: 'Clock Date' },
      { key: 'Quantity', label: 'Quantity' },
      { key: 'OldQuantity', label: 'Old Quantity' },
      { key: 'Rate', label: 'Rate' },
      { key: 'Delta', label: 'Delta' },
    ],
    summaryData: [
      { id: 's3', state: 'confirmed', RecordID: '3001',
        EmployeeCode: 'E003',
        EmployeeName: 'Zhang San',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        AllowanceCode: 'ATT',
        AllowanceName: 'Attendance',
        ClockDate: '2026-04-12',
        Quantity: '8.00',
        OldQuantity: '9.00',
        Rate: '1.00',
        Delta: '-1.00',
      },
      { id: 's4', state: 'confirmed', RecordID: '3002',
        EmployeeCode: 'E001',
        EmployeeName: 'Li Si',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        AllowanceCode: 'ATT',
        AllowanceName: 'Attendance',
        ClockDate: '2026-04-15',
        Quantity: '0.00',
        OldQuantity: '8.00',
        Rate: '1.00',
        Delta: '-8.00',
      },
    ],
    detailsColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
      { key: 'ClockDate', label: 'Clock Date' },
      { key: 'Quantity', label: 'Quantity' },
      { key: 'OldQuantity', label: 'Old Quantity' },
      { key: 'Rate', label: 'Rate' },
      { key: 'Delta', label: 'Delta' },
    ],
    detailsData: [
      {
        id: 'a1',
        state: 'confirmed',
        RecordID: '4001',
        EmployeeCode: 'E003',
        EmployeeName: 'Zhang San',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        AllowanceCode: 'ATT',
        AllowanceName: 'Attendance',
        ClockDate: '2026-04-12',
        Quantity: '8.00',
        OldQuantity: '9.00',
        Rate: '1.00',
        Delta: '-1.00',
        issue: 'Continuous Night Shift',
        severity: 'Medium',
      },
      {
        id: 'a2',
        state: 'confirmed',
        RecordID: '4002',
        EmployeeCode: 'E001',
        EmployeeName: 'Li Si',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        AllowanceCode: 'ATT',
        AllowanceName: 'Attendance',
        ClockDate: '2026-04-15',
        Quantity: '0.00',
        OldQuantity: '8.00',
        Rate: '1.00',
        Delta: '-8.00',
        issue: 'Missing clock-in',
        severity: 'High',
      },
      {
        id: 'a3',
        state: 'ignored',
        RecordID: '4003',
        EmployeeCode: 'E002',
        EmployeeName: 'Wang Wu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        AllowanceCode: 'ATT',
        AllowanceName: 'Attendance',
        ClockDate: '2026-04-16',
        Quantity: '8.00',
        OldQuantity: '8.00',
        Rate: '1.00',
        Delta: '0.00',
        issue: 'Late clock-in (exempted)',
        severity: 'Low',
      },
    ]
  },
  ot: {
    summaryColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'OTCompensationCode', label: 'OT Compensation Code' },
      { key: 'OTCompensationName', label: 'OT Compensation Name' },
      { key: 'ClockDate', label: 'Clock Date' },
      { key: 'TimeHours', label: 'Time Hours' },
      { key: 'ApprovalDate', label: 'Approval Date' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    summaryData: [
      { id: 's5', state: 'confirmed', RecordID: '5001',
        EmployeeCode: 'E010',
        EmployeeName: 'Zhao Liu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        OTCompensationCode: 'OT01',
        OTCompensationName: 'Weekend OT',
        ClockDate: '2026-04-11',
        TimeHours: '12.00',
        ApprovalDate: '',
        AllowanceCode: 'OT',
        AllowanceName: 'Overtime',
      },
      { id: 's6', state: 'confirmed', RecordID: '5002',
        EmployeeCode: 'E011',
        EmployeeName: 'Sun Qi',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        OTCompensationCode: 'OT02',
        OTCompensationName: 'Weekday OT',
        ClockDate: '2026-04-13',
        TimeHours: '4.00',
        ApprovalDate: '',
        AllowanceCode: 'OT',
        AllowanceName: 'Overtime',
      },
    ],
    detailsColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'OTCompensationCode', label: 'OT Compensation Code' },
      { key: 'OTCompensationName', label: 'OT Compensation Name' },
      { key: 'ClockDate', label: 'Clock Date' },
      { key: 'TimeHours', label: 'Time Hours' },
      { key: 'ApprovalDate', label: 'Approval Date' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    detailsData: [
      {
        id: 'o1',
        state: 'confirmed',
        RecordID: '6001',
        EmployeeCode: 'E010',
        EmployeeName: 'Zhao Liu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        OTCompensationCode: 'OT01',
        OTCompensationName: 'Weekend OT',
        ClockDate: '2026-04-11',
        TimeHours: '12.00',
        ApprovalDate: '',
        AllowanceCode: 'OT',
        AllowanceName: 'Overtime',
        issue: 'OT Threshold Exceeded',
        severity: 'High',
      },
      {
        id: 'o2',
        state: 'confirmed',
        RecordID: '6002',
        EmployeeCode: 'E011',
        EmployeeName: 'Sun Qi',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        OTCompensationCode: 'OT02',
        OTCompensationName: 'Weekday OT',
        ClockDate: '2026-04-13',
        TimeHours: '4.00',
        ApprovalDate: '',
        AllowanceCode: 'OT',
        AllowanceName: 'Overtime',
        issue: 'Unapproved OT',
        severity: 'Medium',
      },
    ]
  },
  leave: {
    summaryColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'LeaveCode', label: 'Leave Code' },
      { key: 'LeaveName', label: 'Leave Name' },
      { key: 'LeaveAmount', label: 'Leave Amount' },
      { key: 'ApprovalDate', label: 'Approval Date' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    summaryData: [
      { id: 's7', state: 'confirmed', RecordID: '7001',
        EmployeeCode: 'E020',
        EmployeeName: 'Chen BA',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        LeaveCode: 'L01',
        LeaveName: 'Annual Leave',
        LeaveAmount: '0.50',
        ApprovalDate: '2026-04-10',
        AllowanceCode: 'AL',
        AllowanceName: 'Leave Deduction',
      },
      { id: 's8', state: 'confirmed', RecordID: '7002',
        EmployeeCode: 'E021',
        EmployeeName: 'Zhou Jiu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        LeaveCode: 'L02',
        LeaveName: 'Sick Leave',
        LeaveAmount: '2.00',
        ApprovalDate: '',
        AllowanceCode: 'SL',
        AllowanceName: 'Sick Leave Deduction',
      },
    ],
    detailsColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'LeaveCode', label: 'Leave Code' },
      { key: 'LeaveName', label: 'Leave Name' },
      { key: 'LeaveStart', label: 'Leave Start' },
      { key: 'LeaveDate', label: 'Leave Date' },
      { key: 'LeaveAmount', label: 'Leave Amount' },
      { key: 'ApprovalDate', label: 'Approval Date' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    detailsData: [
      {
        id: 'l1',
        state: 'confirmed',
        RecordID: '8001',
        EmployeeCode: 'E020',
        EmployeeName: 'Chen BA',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        LeaveCode: 'L01',
        LeaveName: 'Annual Leave',
        LeaveStart: '2026-04-17',
        LeaveDate: '2026-04-17',
        LeaveAmount: '0.50',
        ApprovalDate: '2026-04-10',
        AllowanceCode: 'AL',
        AllowanceName: 'Leave Deduction',
        issue: 'Abnormal Leave Pattern (Friday)',
        severity: 'Low',
      },
      {
        id: 'l2',
        state: 'confirmed',
        RecordID: '8002',
        EmployeeCode: 'E021',
        EmployeeName: 'Zhou Jiu',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        LeaveCode: 'L02',
        LeaveName: 'Sick Leave',
        LeaveStart: '2026-04-18',
        LeaveDate: '2026-04-19',
        LeaveAmount: '2.00',
        ApprovalDate: '',
        AllowanceCode: 'SL',
        AllowanceName: 'Sick Leave Deduction',
        issue: 'Attendance & Leave Overlap',
        severity: 'High',
      },
    ]
  },
  leave_status: {
    summaryColumns: [],
    summaryData: [],
    detailsColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'LeaveCode', label: 'Leave Code' },
      { key: 'LeaveName', label: 'Leave Name' },
      { key: 'Quantity', label: 'Quantity' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    detailsData: [
      {
        id: 'ls1',
        state: 'confirmed',
        RecordID: '9001',
        EmployeeCode: 'E030',
        EmployeeName: 'Wu Shi',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        LeaveCode: 'L03',
        LeaveName: 'Unpaid Leave',
        Quantity: '3.00',
        AllowanceCode: 'DED',
        AllowanceName: 'Base Pay Deduction',
        issue: 'Pending Leave Impacts Payroll',
        severity: 'High',
      },
    ]
  },
  leave_encash_ye: {
    summaryColumns: [],
    summaryData: [],
    detailsColumns: [
      { key: 'RecordID', label: 'Record ID' },
      { key: 'EmployeeCode', label: 'Employee Code' },
      { key: 'EmployeeName', label: 'Employee Name' },
      { key: 'CompanyCode', label: 'Company Code' },
      { key: 'CompanyName', label: 'Company Name' },
      { key: 'LeaveCode', label: 'Leave Code' },
      { key: 'LeaveName', label: 'Leave Name' },
      { key: 'LeaveStart', label: 'Leave Start' },
      { key: 'LeaveDate', label: 'Leave Date' },
      { key: 'LeaveAmount', label: 'Leave Amount' },
      { key: 'PeriodYear', label: 'Period Year' },
      { key: 'AllowanceCode', label: 'Allowance Code' },
      { key: 'AllowanceName', label: 'Allowance Name' },
    ],
    detailsData: [
      {
        id: 'le1',
        state: 'confirmed',
        RecordID: '10001',
        EmployeeCode: 'E040',
        EmployeeName: 'Zheng Yi',
        CompanyCode: 'C01',
        CompanyName: 'Butter SG',
        LeaveCode: 'LE01',
        LeaveName: 'Annual Leave Encash',
        LeaveStart: '2025-01-01',
        LeaveDate: '2025-12-31',
        LeaveAmount: '5.00',
        PeriodYear: '2025',
        AllowanceCode: 'ENC',
        AllowanceName: 'Leave Encashment',
        issue: 'Encashment Qualification Error',
        severity: 'Medium',
      },
    ]
  },
};
